// Auto-generated embroidery data from markdown files
// Generated on 2025-07-25T13:47:01.595Z

window.EMBROIDERY_DATA = [
  {
    "image": "1.JPEG",
    "category": "stadsgezichten",
    "subcategory": "17de-eeuws",
    "titleNL": "Amstelredam 1650",
    "titleEN": "Amsterdam 1650",
    "descriptionNL": "Dit borduurwerk toont het imposante stadsgezicht van Amsterdam rond 1650, gebaseerd op een gravure van Kaspar Merian uit 1659. De prent maakte deel uit van de reeks Topografia Germania Inferioris en laat een stad zien in volle bloei, met druk scheepvaartverkeer op het IJ en een herkenbare skyline van torens en monumenten.\n\nHet werk brengt op minutieuze wijze de architectonische pracht van de stad in beeld. Gebouwen als de Montelbaanstoren, de Zuiderkerk, de Munttoren en het Oude Stadhuis — nog intact afgebeeld vóór de brand van 1652 — verrijzen uit het linnen met een verbluffend oog voor detail. De skyline weerspiegelt de kracht van de Amsterdamse handelsgeest en de rol van de stad als cultureel en economisch zwaartepunt van de Gouden Eeuw.\n\n---",
    "descriptionEN": "This embroidery presents an imposing cityscape of Amsterdam around the year 1650, based on a 1659 engraving by Kaspar Merian. The print was part of the Topographia Germania Inferioris series and depicts a city in full bloom, with bustling ship traffic on the IJ and a recognizable skyline of towers and monuments.\n\nThe work meticulously renders the architectural splendour of the city. Buildings such as the Montelbaanstoren, the Zuiderkerk, the Munttoren, and the Old Town Hall—still intact here before the fire of 1652—rise from the linen with remarkable attention to detail. The skyline reflects the strength of Amsterdam's mercantile spirit and its role as a cultural and economic epicentre during the Dutch Golden Age.",
    "dimensions": "82x37 cm",
    "price": "€60",
    "technique": "Kruissteek",
    "year": "1650",
    "tags": [
      "amsterdam",
      "gouden eeuw",
      "historisch",
      "stadsgezicht"
    ]
  },
  {
    "image": "2.JPEG",
    "category": "stadsgezichten",
    "subcategory": "markt-plein",
    "titleNL": "Waterlooplein",
    "titleEN": "Waterlooplein",
    "descriptionNL": "Dit borduurwerk vangt de levendige sfeer van het Waterlooplein in Amsterdam, een plek die al eeuwenlang een centrum is van handel en ontmoeting. Afgebeeld is een kleurrijke markt, waar koopmannen en bezoekers tussen de kraampjes struinen, op zoek naar bijzondere vondsten. Dit tafereel doet sterk denken aan de bekende vlooienmarkt die hier al sinds de 19e eeuw wordt gehouden en die het plein zijn unieke karakter geeft.\n\nOp de achtergrond prijkt de Mozes en Aäronkerk, een beeldbepalend monument dat niet alleen de skyline van het plein domineert, maar ook een symbool is van de rijke geschiedenis van de stad. De aanwezigheid van marktkramen, lampen, oude boeken en andere curiosa roept de nostalgie op van een tijd waarin handelaren hun waren uitstalde op kleedjes en onder tentzeilen, en onderhandelingen over prijzen plaatsvonden in de schaduw van historische gebouwen.\n\n---",
    "descriptionEN": "This embroidery, Waterlooplein, beautifully captures the vibrant atmosphere of Amsterdam's historic Waterlooplein, a place renowned since the 19th century as home to one of the city's most famous flea markets. The scene portrays merchants and visitors strolling between stalls, searching for unique finds. The lively depiction evokes the market's distinctive charm, a tradition that continues to give the square its unique character today.\n\nIn the background stands the distinctive Mozes en Aäronkerk, a landmark that contributes greatly to the character of the square and symbolizes Amsterdam's historical heritage. The stalls, filled with second-hand items, recall a nostalgic era when traders laid out their goods on blankets and under tent canopies, negotiating prices in the shadow of historic buildings.",
    "dimensions": "44x61 cm",
    "price": "€45",
    "technique": "Kruissteek",
    "year": "19e eeuw",
    "tags": [
      "amsterdam",
      "historisch",
      "markt",
      "vlooienmarkt",
      "waterlooplein"
    ]
  },
  {
    "image": "3.JPEG",
    "category": "stadsgezichten",
    "subcategory": "iconische-panden",
    "titleNL": "Zicht op Amsterdam",
    "titleEN": "View of Amsterdam",
    "descriptionNL": "Dit borduurwerk werd ontworpen ter gelegenheid van het 700-jarig bestaan van Amsterdam en weerspiegelt de karakteristieke architectuur van de stad. De grachtenpanden met hun uiteenlopende gevelvormen – trapgevels, klokgevels en puntgevels – tonen de historische rijkdom en diversiteit van de stad, die door de eeuwen heen een centrum van handel, cultuur en vernieuwing is geweest.\n\nOp de achtergrond verrijzen iconische torens, verwijzend naar de vele kerken en monumentale bouwwerken die de skyline van Amsterdam bepalen. Hoewel het tafereel geen specifieke locatie weergeeft, ademt het geheel de tijdloze sfeer van de Amsterdamse binnenstad, waar historie en moderniteit hand in hand gaan.\n\n---",
    "descriptionEN": "This embroidery beautifully commemorates the 700th anniversary of Amsterdam. The canal houses with their varied façades—stepped gables, bell gables, and pointed gables—highlight the city's architectural richness and historical diversity. These iconic houses symbolize Amsterdam's long history as a hub of trade, culture, and innovation.\n\nIn the background, several famous towers rise above the houses, evoking Amsterdam's historic skyline. Together, they create a distinctive cityscape, celebrating Amsterdam as a dynamic city that has thrived through centuries of change.",
    "dimensions": "45x9 cm",
    "price": "€50",
    "technique": "Kruissteek",
    "year": "700-jarig jubileum",
    "tags": [
      "700 jaar",
      "amsterdam",
      "architectuur",
      "grachten",
      "grachtenpanden",
      "jubileum",
      "stadsgezicht"
    ]
  },
  {
    "image": "4.JPEG",
    "category": "klederdracht",
    "subcategory": "regio-merklappen",
    "titleNL": "Merklap 1821",
    "titleEN": "Sampler 1821",
    "descriptionNL": "Deze merklap is een zorgvuldig vervaardigde reproductie van een origineel uit 1821, ontstaan binnen de traditie van borduuronderwijs aan de Openbare Werk- en Leerschool in Amsterdam. Dit 19e-eeuwse instituut bood talentvolle, maar kwetsbare meisjes de kans om praktische vaardigheden te ontwikkelen, waaronder het borduren van merklappen. Deze oefenstukken dienden niet alleen als bewijs van hun kunde, maar waren ook een essentiële voorbereiding op een toekomst in de huishoudelijke of textielindustrie.\n\nDe merklap toont een gevarieerd palet aan motieven, waaronder kronen, een molen en een statig grachtenpand, die refereren aan de Nederlandse identiteit en het stedelijke leven. De afwezigheid van de letter J weerspiegelt de vroegere spellingconventies.\n\n---",
    "descriptionEN": "This sampler is a meticulously crafted reproduction of an original from 1821, created within the tradition of embroidery education at the Public Work and Training School in Amsterdam. This 19th-century institution provided talented yet vulnerable girls with the opportunity to develop practical skills, including embroidery. These practice pieces not only served as proof of their craftsmanship but also played a crucial role in preparing them for a future in domestic service or the textile industry.\n\nThe sampler features a diverse array of motifs, including crowns, a windmill, and an elegant canal house, all referencing Dutch identity and urban life. Symbols such as apples and pears—possibly alluding to the appeltjes van Oranje—along with the presence of alphabets and initials, make this sampler a well-documented historical artifact. The absence of the letter \"J\" reflects historical spelling conventions of the time.",
    "dimensions": "57x66 cm",
    "price": "€40",
    "technique": "Kruissteek",
    "year": "1821",
    "tags": [
      "19e eeuw",
      "amsterdam",
      "merklap",
      "onderwijs",
      "reproductie",
      "sampler"
    ]
  },
  {
    "image": "5.JPEG",
    "category": "koninklijk",
    "subcategory": "wapens-deviezen",
    "titleNL": "Je Maintiendrai",
    "titleEN": "Je Maintiendrai",
    "descriptionNL": "Dit borduurwerk toont het Koninklijk Wapen van Nederland, geflankeerd door twee gouden leeuwen en bekroond met een vorstelijke kroon. De spreuk *Je Maintiendrai* (\"Ik zal handhaven\") is sinds de tijd van Willem van Oranje verbonden aan het Huis van Oranje en symboliseert de continuïteit en standvastigheid van de Nederlandse monarchie.\n\nHet wapen werd officieel vastgesteld in 1815, bij de oprichting van het Koninkrijk der Nederlanden. De iconografie van het schild en de leeuwen herinnert aan de dynastieke en militaire geschiedenis van het land. Dit borduurwerk is niet alleen een kunstzinnige weergave van nationale trots, maar ook een eerbetoon aan de heraldiek die generaties lang in Nederland werd gekoesterd.",
    "descriptionEN": "This embroidery features the Royal Coat of Arms of the Netherlands, flanked by two golden lions and crowned with a regal crown. The motto Je Maintiendrai (\"I shall maintain\") has been associated with the House of Orange since the time of William of Orange and symbolizes the continuity and steadfastness of the Dutch monarchy.\n\nThe coat of arms was officially established in 1815, at the founding of the Kingdom of the Netherlands. The shield's iconography and the lions serve as reminders of the country's dynastic and military history. This embroidery is not only an artistic representation of national pride but also a tribute to the heraldic tradition that has been cherished in the Netherlands for generations.",
    "dimensions": "25x21 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "1815",
    "tags": [
      "heraldiek",
      "je maintiendrai",
      "koninklijk wapen",
      "kroon",
      "leeuwen",
      "oranje",
      "royal coat of arms"
    ]
  },
  {
    "image": "6.JPEG",
    "category": "stadsgezichten",
    "subcategory": "algemeen-stadsgezicht",
    "titleNL": "De Evolutie van de Fiets",
    "titleEN": "The Evolution of the Bicycle",
    "descriptionNL": "Dit borduurwerk viert de evolutie van de fiets, een onmisbaar symbool van de Nederlandse cultuur. Door de eeuwen heen hebben verschillende ontwerpen bijgedragen aan de ontwikkeling van de fiets zoals we die vandaag kennen. Dit werk toont de transitie van de vroege loopfiets naar de Hoge Bi en uiteindelijk de moderne toerfiets.\n\nDe aanwezigheid van Nederlandse vlaggetjes onderstreept de prominente rol die Nederland speelt als fietsland. Het werk is niet alleen een ode aan de technologische vooruitgang, maar ook aan de duurzame en praktische mentaliteit die de fiets zo diep in de Nederlandse samenleving heeft verankerd.",
    "descriptionEN": "This embroidery celebrates the evolution of the bicycle, an essential symbol of Dutch culture. Over the centuries, various designs have contributed to the development of the bicycle as we know it today. This piece illustrates the transition from the early dandy horse to the penny-farthing and, ultimately, the modern touring bicycle.\n\nThe presence of Dutch flags highlights the prominent role of the Netherlands as a cycling nation. This work is not only a tribute to technological progress but also to the sustainable and practical mindset that has made the bicycle an integral part of Dutch society.",
    "dimensions": "24x61 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "bicycle",
      "duurzaam",
      "evolutie",
      "evolution",
      "fiets",
      "nederland",
      "transport"
    ]
  },
  {
    "image": "7.JPEG",
    "category": "flora",
    "subcategory": "kamer-wilde-bloemen",
    "titleNL": "Kaaps Viooltje",
    "titleEN": "African Violet",
    "descriptionNL": "Dit borduurwerk vangt de delicate schoonheid van het Kaaps viooltje, een plant die al generaties lang geliefd is als kamerplant. De fluweelachtige bloemblaadjes en levendige kleuren maken deze bloem tot een favoriet in vele huishoudens. Het subtiele kleurgebruik en de fijne steken brengen de plant met een bijzondere zachtheid tot leven.\n\nBorduurwerken zoals deze illustreren de waardering voor flora binnen de textiele kunst en laten zien hoe natuur en creativiteit samenkomen in een tijdloos handwerk.",
    "descriptionEN": "This embroidery captures the delicate beauty of the African violet, a plant cherished for generations as a beloved houseplant. Its velvety petals and vibrant colors have made it a favorite in many homes. The subtle use of color and fine stitches bring this plant to life with remarkable softness.\n\nEmbroideries like this illustrate an appreciation for flora within textile art, showcasing how nature and creativity merge in a timeless craft.",
    "dimensions": "22x22 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "african violet",
      "bloem",
      "bloemen",
      "flora",
      "flowers",
      "houseplant",
      "kaaps viooltje",
      "kamerplant",
      "natuur",
      "plant"
    ]
  },
  {
    "image": "10.JPEG",
    "category": "flora",
    "subcategory": "bloembollenlandschap",
    "titleNL": "De Bollenstreek",
    "titleEN": "The Bulb Region",
    "descriptionNL": "Dit borduurwerk verbeeldt een iconisch Nederlands landschap: uitgestrekte bollenvelden in volle bloei, met rijen tulpen, narcissen en hyacinten in levendige kleuren. Kasteel Keukenhof prijkt hoog aan de horizon als een stille getuige van de geschiedenis van de streek.\n\nOp de voorgrond brengen kinderen de sfeer tot leven door handgemaakte bloemenkettingen te verkopen aan toeristen, terwijl paardenkoetsen, fietsers en feestelijke praalwagens een levendig beeld schetsen van de jaarlijkse viering van de lente. Dit tafereel vangt de charme en traditie van de bollenstreek en laat zien hoe natuur en cultuur hier samenkomen.",
    "descriptionEN": "This embroidery depicts an iconic Dutch landscape: vast flower bulb fields in full bloom, with rows of tulips, daffodils, and hyacinths in vibrant colors. Keukenhof Castle stands proudly on the horizon, a silent witness to the region's rich history.\n\nIn the foreground, children bring the scene to life by selling handmade flower garlands to tourists, while horse-drawn carriages, cyclists, and festive parade floats create a lively impression of the annual spring celebration. This piece captures the charm and tradition of the bulb region, showcasing the harmony between nature and culture.",
    "dimensions": "35x56 cm",
    "price": "€45",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "bloem",
      "bollenstreek",
      "bollenvelden",
      "bulb region",
      "keukenhof",
      "lente",
      "natuur",
      "spring",
      "tulips",
      "tulpen"
    ]
  },
  {
    "image": "11.JPEG",
    "category": "klederdracht",
    "subcategory": "traditionele-kostuums",
    "titleNL": "Merklap Oud West-Friesland",
    "titleEN": "Sampler Oud West-Friesland",
    "descriptionNL": "Dit borduurwerk eert West-Friesland, een streek in Noord-Holland met een rijke geschiedenis en een diepgewortelde agrarische traditie. De regio ontleent haar naam aan een tijd waarin zij nog deel uitmaakte van het grotere Friesland. Onafhankelijke geest en vakmanschap kenmerken de West-Friese identiteit, zichtbaar in de historische architectuur, stolpboerderijen en uitgestrekte weilanden.\n\nDe afgebeelde elementen, zoals traditionele gebouwen en landschappen, weerspiegelen de culturele eigenheid van West-Friesland en herinneren aan een tijd waarin handel, ambacht en landbouw de regio lieten floreren. Dit borduurwerk brengt niet alleen deze geschiedenis tot leven, maar is ook een tastbare uiting van regionale trots en erfgoed.",
    "descriptionEN": "This embroidery honors West Friesland, a region in North Holland with a rich history and a deep-rooted agricultural tradition. The area derives its name from a time when it was still part of the larger Friesland. Independence and craftsmanship define the West Frisian identity, reflected in its historic architecture, stolp farmhouses, and vast meadows.\n\nThe depicted elements, such as traditional buildings and landscapes, showcase the cultural character of West Friesland and recall an era when trade, craftsmanship, and agriculture allowed the region to flourish. This embroidery not only brings that history to life but also serves as a tangible expression of regional pride and heritage.",
    "dimensions": "30x50 cm",
    "price": "€45",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "agrarisch",
      "erfgoed",
      "heritage",
      "merklap",
      "noord-holland",
      "sampler",
      "west-friesland"
    ]
  },
  {
    "image": "12.JPEG",
    "category": "zaanse",
    "subcategory": "zaanse-schans",
    "titleNL": "De Zaanse Schans",
    "titleEN": "The Zaanse Schans",
    "descriptionNL": "De Zaanse Schans, een van de meest iconische plekken in Nederland, weerspiegelt de rijke geschiedenis van ambacht en industrie langs de Zaan. Dit borduurwerk vangt de essentie van dit historische gebied, waar houten huizen, draaiende molens en schilderachtige bruggen samenkomen tot een tijdloos tafereel.\n\nSinds de oprichting in de jaren 60 als openluchtmuseum is de Zaanse Schans uitgegroeid tot een levend monument van het Nederlandse erfgoed. Bezoekers krijgen hier een inkijk in traditionele ambachten zoals klompen maken en kaasmaken. De karakteristieke groene gevels en witte houten randen van de huizen, evenals de brug met toeristen, benadrukken de blijvende aantrekkingskracht van deze bijzondere plek.",
    "descriptionEN": "The Zaanse Schans, one of the most iconic locations in the Netherlands, reflects the rich history of craftsmanship and industry along the Zaan River. This embroidery captures the essence of this historic area, where wooden houses, spinning windmills, and picturesque bridges come together in a timeless scene.\n\nSince its establishment as an open-air museum in the 1960s, the Zaanse Schans has become a living monument to Dutch heritage. Visitors can experience traditional crafts such as clog-making and cheese-making. The characteristic green facades and white wooden trims of the houses, along with the bridge filled with tourists, highlight the enduring appeal of this unique place.",
    "dimensions": "62x24 / 70x25 / 65x22 cm",
    "price": "€50",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "ambacht",
      "craftsmanship",
      "erfgoed",
      "heritage",
      "molens",
      "windmills",
      "zaan",
      "zaanse",
      "zaanse schans"
    ]
  },
  {
    "image": "13.JPEG",
    "category": "zaanse",
    "subcategory": "zaan-sampler",
    "titleNL": "Merklap Nederland",
    "titleEN": "Sampler Netherlands",
    "descriptionNL": "Deze merklap is een kunstzinnige weergave van typisch Nederlandse iconografie, vervaardigd met oog voor detail en traditie. Merklappen dienden oorspronkelijk als oefenstukken voor jonge borduursters, maar groeiden uit tot waardevolle erfstukken waarin persoonlijke, religieuze en regionale symboliek samensmolten.\n\nDe afbeelding toont een verzameling van iconische Hollandse elementen: een Zaans huisje, grachtenpanden, een ophaalbrug, een molen, een trekschuit en een paard en wagen.\n\nMet zijn rijke detaillering en karakteristieke Hollandse sfeer weerspiegelt deze merklap de verbondenheid met het culturele erfgoed van Nederland.",
    "descriptionEN": "This sampler is an artistic representation of quintessential Dutch iconography, crafted with attention to detail and tradition. Originally, samplers served as practice pieces for young embroiderers, but they evolved into treasured heirlooms where personal, religious, and regional symbolism merged.\n\nThe design features a collection of iconic Dutch elements: a Zaanse house, canal houses, a drawbridge, a windmill, a tow barge, and a horse and carriage.\n\nWith its rich detailing and characteristic Dutch ambiance, this sampler reflects a deep connection to the cultural heritage of the Netherlands.",
    "dimensions": "44x60 cm",
    "price": "€40",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "erfgoed",
      "grachten",
      "hollands",
      "iconografie",
      "merklap",
      "nederland",
      "sampler",
      "zaan",
      "zaanse"
    ]
  },
  {
    "image": "14.JPEG",
    "category": "delfts",
    "subcategory": "postzegel-borduurwerken",
    "titleNL": "Postzegel 45 cent – Koningin Juliana",
    "titleEN": "Postage Stamp 45 Cents – Queen Juliana",
    "descriptionNL": "Dit borduurwerk is gebaseerd op een iconische Nederlandse postzegel met het portret van Koningin Juliana, die het land regeerde van 1948 tot 1980. Haar beeltenis werd veelvuldig gebruikt op postzegels, vaak in sobere, gestileerde vorm, wat haar imago van nabijheid en eenvoud onderstreepte. Deze uiting van filatelistische kunst brengt een stukje vaderlandse geschiedenis in textiel tot leven.\n\nPostzegels dienden niet alleen als betaalmiddel voor postverkeer, maar waren ook een middel om nationale trots en grafisch vakmanschap tot uiting te brengen.\n\nDit borduurwerk brengt de geschiedenis van het Nederlandse koningshuis en de traditie van postzegelverzameling op artistieke wijze tot leven. Het verbindt filatelie en handwerk, twee verzamelculturen die in Nederland een rijke historie kennen.",
    "descriptionEN": "This embroidery is based on an iconic Dutch postage stamp featuring Queen Juliana, who reigned from 1948 to 1980. Her portrait appeared frequently on stamps, often in a modest, stylized form that emphasized her image of approachability and simplicity. This expression of philatelic art brings a piece of national history to life in textile form.\n\nPostage stamps served not only as a means of payment for mail but also as a medium for expressing national pride and graphic craftsmanship.\n\nThis embroidery artistically revives the history of the Dutch royal family and the tradition of stamp collecting. It bridges philately and needlework—two collecting cultures with a rich heritage in the Netherlands.",
    "dimensions": "15x20 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "filatelie",
      "juliana",
      "koningin",
      "philately",
      "postage stamp",
      "postzegel",
      "queen"
    ]
  },
  {
    "image": "15.JPEG",
    "category": "delfts",
    "subcategory": "postzegel-borduurwerken",
    "titleNL": "Postzegel 10 cent – Koningin Wilhelmina",
    "titleEN": "Postage Stamp 10 Cents – Queen Wilhelmina",
    "descriptionNL": "Dit borduurwerk is geïnspireerd op een klassieke Nederlandse postzegel met het portret van Koningin Wilhelmina, een vorstin die bijna zestig jaar lang het land regeerde. Haar beeld op postzegels symboliseert niet alleen de monarchie, maar ook een periode van grote veranderingen en historische gebeurtenissen in Nederland, waaronder beide wereldoorlogen.\n\nDe postzegel met een nominale waarde van 10 cent toont Wilhelmina in een gestileerde, herkenbare vorm, zoals zij op vele postzegels is afgebeeld. Postzegels waren ooit een essentieel communicatiemiddel en vormden daarnaast een geliefd verzamelobject, waarin nationale trots en grafisch ontwerp samenkwamen.\n\nDit borduurwerk eert zowel de geschiedenis van het Nederlandse koningshuis als de traditie van filatelie, waarin iconische postzegels werden vereeuwigd als waardevolle erfstukken.",
    "descriptionEN": "This embroidery is inspired by a classic Dutch postage stamp featuring the portrait of Queen Wilhelmina, who reigned for nearly sixty years. Her image on postage stamps symbolizes not only the monarchy but also an era of great change and historical events in the Netherlands, including both World Wars.\n\nThe 10-cent stamp presents Wilhelmina in a stylized, recognizable form, as seen on many Dutch stamps. Once an essential means of communication, postage stamps also became beloved collectibles, where national pride and graphic design converged.\n\nThis embroidery honors both the history of the Dutch royal family and the tradition of philately, in which iconic postage stamps were immortalized as treasured heirlooms.",
    "dimensions": "15x20 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "filatelie",
      "koningin",
      "philately",
      "postage stamp",
      "postzegel",
      "queen",
      "wilhelmina"
    ]
  },
  {
    "image": "19.JPEG",
    "category": "flora",
    "subcategory": "kamer-wilde-bloemen",
    "titleNL": "Korenbloemen",
    "titleEN": "Cornflowers",
    "descriptionNL": "Dit borduurwerk is een ode aan de korenbloem (Centaurea cyanus), een van de meest herkenbare en geliefde wilde bloemen van Nederland. Met zijn heldere blauwe kleur sierde deze bloem eeuwenlang de korenvelden en akkers, waar hij samen met klaprozen en margrieten een schilderachtig landschap vormde.\n\nDe korenbloem heeft niet alleen een esthetische waarde, maar ook een rijke symboliek. In de folklore wordt de bloem vaak geassocieerd met geluk, trouw en eenvoud. Door de opkomst van intensieve landbouw en herbiciden is de wilde korenbloem tegenwoordig een zeldzamer verschijnsel, wat dit borduurwerk des te waardevoller maakt als herinnering aan het Nederlandse platteland van weleer.",
    "descriptionEN": "This embroidery is an ode to the cornflower (Centaurea cyanus), one of the most recognizable and beloved wildflowers in the Netherlands. With its vibrant blue color, it once flourished in cornfields and meadows, creating a picturesque landscape alongside poppies and daisies.\n\nBeyond its beauty, the cornflower carries deep symbolism. In folklore, it is associated with luck, loyalty, and simplicity. Due to intensive farming and herbicides, wild cornflowers have become increasingly rare, making this embroidery a valuable tribute to the Dutch countryside of the past.",
    "dimensions": "26x34 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "akkers",
      "blauw",
      "bloem",
      "blue",
      "cornflowers",
      "korenbloem",
      "korenbloemen",
      "wilde bloemen",
      "wildflowers"
    ]
  },
  {
    "image": "21.JPEG",
    "category": "koninklijk",
    "subcategory": "inhuldigingen-geboorte",
    "titleNL": "Merklap geboorte prinses Beatrix",
    "titleEN": "Sampler – Birth of Princess Beatrix",
    "descriptionNL": "Deze bijzondere merklap markeert de geboorte van prinses Beatrix op 31 januari 1938, een historisch moment voor Nederland. In de traditie van koninklijke herdenkingen werd de komst van een nieuwe troonopvolger vaak gevierd met handwerk, waarin symboliek en nationale trots samenkwamen.\n\nHet borduurwerk bevat klassieke elementen die verwijzen naar de Oranjes, zoals de nationale kleuren, een koninklijke kroon en florale motieven die de verbondenheid met het Huis van Oranje benadrukken.\n\nDe geboorte van prinses Beatrix was een moment van nationale eenheid en vreugde, en dit borduurwerk weerspiegelt de warme gevoelens die daarmee gepaard gingen. Het draagt de sporen van een traditie waarin textiel werd gebruikt om geschiedenis tastbaar te maken en koninklijke gebeurtenissen in de huiselijke sfeer te vereeuwigen.",
    "descriptionEN": "This special sampler commemorates the birth of Princess Beatrix on January 31, 1938—a historic moment for the Netherlands. In the tradition of royal commemorations, the arrival of a new heir to the throne was often celebrated with needlework, combining symbolism and national pride.\n\nThe embroidery features classic elements associated with the House of Orange, such as the national colors, a royal crown, and floral motifs emphasizing the bond with the royal family.\n\nThe birth of Princess Beatrix was a moment of national unity and joy, and this embroidery reflects the warm sentiments that accompanied it. It bears the marks of a tradition in which textiles were used to make history tangible and to commemorate royal milestones in the domestic sphere.",
    "dimensions": "44x66 cm",
    "price": "€40",
    "technique": "borduurwerk",
    "year": "1938",
    "tags": [
      "1938",
      "beatrix",
      "birth",
      "geboorte",
      "koninklijk",
      "merklap",
      "oranje",
      "princess",
      "prins",
      "prinses",
      "royal",
      "sampler"
    ]
  },
  {
    "image": "22.JPEG",
    "category": "zaanse",
    "subcategory": "zaanse-schans",
    "titleNL": "Zaanse Molens",
    "titleEN": "Zaanse Windmills",
    "descriptionNL": "De Zaanse Schans is een levend monument van Nederlands erfgoed, een plek waar de molens en ambachtshuizen de geschiedenis tastbaar maken. Dit borduurwerk toont de iconische windmolens, die eeuwenlang symbool stonden voor innovatie en vakmanschap in de Zaanstreek. De Zaanstreek was in de 17e en 18e eeuw een van de eerste industriegebieden ter wereld, waar honderden molens zorgden voor de verwerking van hout, olie, graan en andere grondstoffen.\n\nMet de opkomst van moderne technieken verdwenen veel molens, maar dankzij behoud en restauratie blijft de Zaanse Schans een plek waar deze bijzondere bouwwerken in volle glorie te bewonderen zijn. Dit borduurwerk vangt niet alleen het landschap, maar ook de geest van een tijdperk waarin windenergie de drijvende kracht was achter de Hollandse handelsgeest.",
    "descriptionEN": "The Zaanse Schans is a living monument of Dutch heritage, a place where windmills and artisan houses bring history to life. This embroidery depicts the iconic windmills that have symbolized innovation and craftsmanship in the Zaan region for centuries. In the 17th and 18th centuries, this area became one of the world's first industrial zones, with hundreds of windmills processing wood, oil, grain, and other raw materials.\n\nWith the rise of modern technology, many windmills disappeared, but through preservation and restoration, the Zaanse Schans remains a place where these remarkable structures can still be admired in their full glory. This embroidery captures not only the landscape but also the spirit of an era when wind power drove the Dutch economy and trade.",
    "dimensions": "65x27 cm",
    "price": "€50",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "erfgoed",
      "heritage",
      "industrie",
      "industry",
      "landscape",
      "landschap",
      "molens",
      "windmills",
      "zaan",
      "zaanse",
      "zaanse schans"
    ]
  },
  {
    "image": "23.JPEG",
    "category": "zaanse",
    "subcategory": "zaanse-schans",
    "titleNL": "Houten Huisjes van de Zaanstreek",
    "titleEN": "Wooden Houses of the Zaan Region",
    "descriptionNL": "De traditionele houten huisjes van de Zaanse Schans zijn een herkenbaar en geliefd onderdeel van het Nederlandse erfgoed. Dit borduurwerk toont de karakteristieke groene gevels, witte kozijnen en sierlijke dakranden die typerend zijn voor deze historische bouwstijl. De Zaanse huisjes weerspiegelen de welvaart en het vakmanschap van de regio, waar molens en ambachtshuizen hand in hand gingen in een bloeiende handelsgemeenschap.\n\nDe Zaanse Schans is niet alleen een museum, maar een levend stukje geschiedenis. De huisjes die hier staan, zijn in de 20e eeuw verzameld en opnieuw opgebouwd om het unieke karakter van de regio te behouden. Dit borduurwerk brengt deze tijdloze schoonheid tot leven en laat zien hoe architectuur en natuur harmonieus samenkomen.",
    "descriptionEN": "The traditional wooden houses of the Zaanse Schans are a recognizable and cherished part of Dutch heritage. This embroidery captures the distinctive green facades, white window frames, and ornate roof edges that define this historic architectural style. The Zaanse houses reflect the prosperity and craftsmanship of the region, where windmills and artisan workshops thrived within a flourishing trade community.\n\nThe Zaanse Schans is not just a museum but a living piece of history. The houses standing there today were carefully relocated and reconstructed in the 20th century to preserve the unique character of the region. This embroidery brings this timeless beauty to life, illustrating how architecture and nature harmoniously coexist.",
    "dimensions": "19x11 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "architecture",
      "architectuur",
      "erfgoed",
      "heritage",
      "houten huisjes",
      "traditional",
      "traditioneel",
      "wooden houses",
      "zaan",
      "zaanse",
      "zaanse schans"
    ]
  },
  {
    "image": "23 b.JPEG",
    "category": "zaanse",
    "subcategory": "zaanse-schans",
    "titleNL": "Houten Huisjes van de Zaanstreek",
    "titleEN": "Wooden Houses of the Zaan Region",
    "descriptionNL": "De traditionele houten huisjes van de Zaanse Schans zijn een herkenbaar en geliefd onderdeel van het Nederlandse erfgoed. Dit borduurwerk toont de karakteristieke groene gevels, witte kozijnen en sierlijke dakranden die typerend zijn voor deze historische bouwstijl. De Zaanse huisjes weerspiegelen de welvaart en het vakmanschap van de regio, waar molens en ambachtshuizen hand in hand gingen in een bloeiende handelsgemeenschap.\n\nDe Zaanse Schans is niet alleen een museum, maar een levend stukje geschiedenis. De huisjes die hier staan, zijn in de 20e eeuw verzameld en opnieuw opgebouwd om het unieke karakter van de regio te behouden. Dit borduurwerk brengt deze tijdloze schoonheid tot leven en laat zien hoe architectuur en natuur harmonieus samenkomen.",
    "descriptionEN": "The traditional wooden houses of the Zaanse Schans are a recognizable and cherished part of Dutch heritage. This embroidery captures the distinctive green facades, white window frames, and ornate roof edges that define this historic architectural style. The Zaanse houses reflect the prosperity and craftsmanship of the region, where windmills and artisan workshops thrived within a flourishing trade community.\n\nThe Zaanse Schans is not just a museum but a living piece of history. The houses standing there today were carefully relocated and reconstructed in the 20th century to preserve the unique character of the region. This embroidery brings this timeless beauty to life, illustrating how architecture and nature harmoniously coexist.",
    "dimensions": "23x14 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "architecture",
      "architectuur",
      "erfgoed",
      "heritage",
      "houten huisjes",
      "traditional",
      "traditioneel",
      "wooden houses",
      "zaan",
      "zaanse",
      "zaanse schans"
    ]
  },
  {
    "image": "25.JPEG",
    "category": "koninklijk",
    "subcategory": "inhuldigingen-geboorte",
    "titleNL": "De Gouden Koets: Het Huwelijk van Beatrix en Claus",
    "titleEN": "The Golden Carriage: The Wedding of Beatrix and Claus",
    "descriptionNL": "Op 10 maart 1966 gaven prinses Beatrix en prins Claus elkaar het jawoord, een gebeurtenis die door heel Nederland werd gevierd. Dit borduurwerk toont de Gouden Koets, het rijtuig dat sinds 1901 door het Nederlandse koningshuis wordt gebruikt bij bijzondere gelegenheden.\n\nHet huwelijk van Beatrix en Claus was meer dan een koninklijke gebeurtenis; het markeerde een tijd van sociale verandering. Prins Claus, van Duitse afkomst, werd aanvankelijk met enige terughoudendheid ontvangen, maar groeide uit tot een van de meest geliefde leden van het koningshuis. De bruiloft luidde een modernere benadering van het koningschap in, waarin de band tussen het koningshuis en het volk steeds centraler kwam te staan.",
    "descriptionEN": "On March 10, 1966, Princess Beatrix and Prince Claus exchanged vows in a wedding celebrated across the Netherlands. This embroidery depicts the Golden Carriage, the royal coach that has been used by the Dutch monarchy for special occasions since 1901.\n\nThe marriage of Beatrix and Claus was more than just a royal event; it marked a time of social change. Prince Claus, of German descent, was initially met with some reservation but later became one of the most beloved members of the royal family. The wedding signified the beginning of a more modern approach to monarchy, where the connection between the royal family and the Dutch people grew increasingly important.",
    "dimensions": "80x30 cm / 36x34 cm",
    "price": "€55",
    "technique": "borduurwerk",
    "year": "1966",
    "tags": [
      "1966",
      "beatrix",
      "claus",
      "golden carriage",
      "gouden koets",
      "huwelijk",
      "koning",
      "koninklijk",
      "prins",
      "prinses",
      "royal",
      "wedding"
    ]
  },
  {
    "image": "26.JPEG",
    "category": "stadsgezichten",
    "subcategory": "iconische-panden",
    "titleNL": "Nederland",
    "titleEN": "The Netherlands in Stitch",
    "descriptionNL": "Dit borduurwerk biedt een gedetailleerd en levendig overzicht van Nederland, met verwijzingen naar de stadsgezichten, provincies en culturele iconen die het land zo uniek maken. De wapens, historische bouwwerken en regionale kenmerken zijn zorgvuldig weergegeven, waardoor het werk niet alleen een kunstzinnige weergave is, maar ook een visuele reis door de Nederlandse geschiedenis en identiteit.\n\nVan de tulpenvelden en molens tot de grachtenpanden en visserijtradities – dit borduurwerk brengt de verscheidenheid van Nederland in beeld. De aanwezigheid van zowel nationale symbolen als herkenbare regionale details maakt het een prachtig eerbetoon aan het erfgoed van ons land.",
    "descriptionEN": "This embroidery provides a detailed and vibrant depiction of the Netherlands, incorporating references to cities, provinces, and cultural icons that make the country so unique. Coats of arms, historical buildings, and regional characteristics are carefully represented, making this piece not only an artistic expression but also a visual journey through Dutch history and identity.\n\nFrom tulip fields and windmills to canal houses and fishing traditions, this embroidery captures the diversity of the Netherlands. The combination of national symbols and recognizable regional details makes it a beautiful tribute to the country's rich heritage.",
    "dimensions": "25x30 cm",
    "price": "",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "coats of arms",
      "culture",
      "cultuur",
      "erfgoed",
      "grachten",
      "heritage",
      "nederland",
      "netherlands",
      "regional features",
      "regionale kenmerken",
      "wapens"
    ]
  },
  {
    "image": "27.JPEG",
    "category": "koninklijk",
    "subcategory": "inhuldigingen-geboorte",
    "titleNL": "Geboortelap Prinses Amalia",
    "titleEN": "Birth Sampler – Princess Amalia",
    "descriptionNL": "Op 7 december 2003 werd prinses Catharina-Amalia geboren, de eerste dochter van koning Willem-Alexander en koningin Máxima. Dit borduurwerk, ontworpen als een geboortelap, weerspiegelt zowel de Nederlandse als Argentijnse invloeden die haar afkomst kenmerken.\n\nHet werk toont een baby met een kroon, omringd door appeltjes van oranje en de woorden Welkom en Bienvenido, een knipoog naar haar dubbele culturele achtergrond. Daarnaast zien we traditionele symbolen van hoop en liefde, evenals speelse elementen die verwijzen naar haar kindertijd.\n\nGeboortelappen zijn een oude traditie, waarin belangrijke momenten in het leven met borduurwerk werden vastgelegd. Dit stuk is niet alleen een herinnering aan de geboorte van een toekomstige koningin, maar ook een weerspiegeling van de warme gevoelens die in Nederland heersten bij haar komst.",
    "descriptionEN": "On December 7, 2003, Princess Catharina-Amalia was born, the first daughter of King Willem-Alexander and Queen Máxima. Designed as a birth sampler, this embroidery reflects both Dutch and Argentine influences, honoring her multicultural heritage.\n\nThe piece features a baby wearing a crown, surrounded by oranges and the words \"Welkom\" and \"Bienvenido\", a nod to her dual cultural background. Traditional symbols of hope and love appear alongside playful elements referencing her early childhood.\n\nBirth samplers are a long-standing tradition, using embroidery to commemorate significant life events. This piece is not only a tribute to the birth of a future queen but also a reflection of the warm sentiments that accompanied her arrival in the Netherlands.",
    "dimensions": "39x31 cm",
    "price": "€30",
    "technique": "borduurwerk",
    "year": "2003",
    "tags": [
      "2003",
      "amalia",
      "birth",
      "catharina-amalia",
      "geboorte",
      "geboortelap",
      "koning",
      "koningin",
      "koninklijk",
      "multicultural",
      "multicultureel",
      "oranje",
      "prins",
      "prinses",
      "royal",
      "sampler"
    ]
  },
  {
    "image": "28.JPEG",
    "category": "delfts",
    "subcategory": "tegelmotieven",
    "titleNL": "Tegel met Molen",
    "titleEN": "Windmill in Delft Blue",
    "descriptionNL": "Delfts blauwe tegels vormen een iconisch onderdeel van het Nederlandse erfgoed en worden al sinds de 17e eeuw vervaardigd. Dit borduurwerk brengt deze traditie tot leven met een afbeelding van een molen, een van de meest kenmerkende symbolen van Nederland.\n\nOorspronkelijk werden Delfts blauwe tegels met de hand beschilderd en sierden ze de wanden van huizen, schouwen en openbare gebouwen. De combinatie van diepe blauwe tinten op een witte achtergrond werd geïnspireerd door Chinees porselein en groeide uit tot een tijdloos decoratief element.\n\nDe molen in dit borduurwerk benadrukt de rol die windmolens speelden in de Nederlandse geschiedenis, van het malen van graan tot het droogleggen van polders. Dit stukje handwerk eert zowel de ambachtelijke traditie van tegelkunst als het agrarische en technische vernuft waar Nederland om bekendstaat.",
    "descriptionEN": "Delft Blue tiles are an iconic part of Dutch heritage and have been crafted since the 17th century. This embroidery brings that tradition to life with the image of a windmill, one of the most recognizable symbols of the Netherlands.\n\nOriginally, Delft Blue tiles were hand-painted and adorned the walls of homes, fireplaces, and public buildings. The deep blue tones on a white background were inspired by Chinese porcelain and evolved into a timeless decorative element.\n\nThe windmill in this embroidery highlights the historic role of windmills in the Netherlands, from grinding grain to reclaiming land from water. This piece of craftsmanship honors both the artisanal tradition of tile-making and the agricultural and technical ingenuity for which the Netherlands is renowned.",
    "dimensions": "16x15 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "blauw",
      "ceramics",
      "delft",
      "delft blue",
      "delfts blauw",
      "keramiek",
      "molen",
      "tegel",
      "tile",
      "traditional",
      "traditioneel",
      "windmill"
    ]
  },
  {
    "image": "29.JPEG",
    "category": "delfts",
    "subcategory": "tegelmotieven",
    "titleNL": "Tegel met Stokpaardjes",
    "titleEN": "Hobby Horses in Delft Blue",
    "descriptionNL": "Speelse scènes en alledaagse taferelen zijn een terugkerend thema in de Delftse tegelkunst. Dit borduurwerk toont een klassiek tafereel van twee kinderen op stokpaardjes, een herinnering aan de eenvoud en fantasie van het kinderleven in vroegere tijden.\n\nDelfts blauwe tegels werden niet alleen gebruikt als decoratie, maar ook om verhalen te vertellen. Scènes met spelende kinderen, boeren op het land en ambachtslieden aan het werk waren geliefd en sierden keukens, haarden en gangen in huizen door heel Nederland.\n\nDit borduurwerk vangt die nostalgische charme en brengt een stukje van deze kunsttraditie naar het textiele ambacht. Het roept een beeld op van een tijd waarin kinderspelen nog eenvoudig en onbezorgd waren en herinnert ons eraan hoe volkskunst generaties lang werd doorgegeven.",
    "descriptionEN": "Playful scenes and everyday life were recurring themes in Delft Blue tile art. This embroidery captures a classic depiction of two children playing with hobby horses, evoking the simplicity and imagination of childhood in earlier times.\n\nDelft Blue tiles were not only used for decoration but also to tell stories. Scenes of playing children, farmers at work, and artisans in their workshops were widely cherished and adorned kitchens, fireplaces, and hallways in homes across the Netherlands.\n\nThis embroidery preserves that nostalgic charm, bringing a piece of this artistic tradition into textile craft. It recalls a time when children's games were simple and carefree, reminding us of how folk art was passed down through generations.",
    "dimensions": "14x14 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "blauw",
      "children",
      "delft",
      "delft blue",
      "delfts blauw",
      "hobby horses",
      "kinderen",
      "nostalgic",
      "nostalgisch",
      "playful",
      "speels",
      "stokpaardjes",
      "tegel",
      "tile"
    ]
  },
  {
    "image": "30.JPEG",
    "category": "koninklijk",
    "subcategory": "wapens-deviezen",
    "titleNL": "Inhuldigingsmerklap Beatrix 1980",
    "titleEN": "Inauguration Sampler – Beatrix 1980",
    "descriptionNL": "Op 30 april 1980 werd prinses Beatrix ingehuldigd als koningin der Nederlanden, een moment van nationale trots en verandering. Dit borduurwerk viert deze historische gebeurtenis met symbolen die verbonden zijn met het koningshuis, zoals het koninklijk wapen, de kroon en de nationale kleuren.\n\nDe inhuldiging van Beatrix betekende het begin van een nieuwe fase voor het Nederlandse koningshuis, waarin zij als staatshoofd een verbindende rol speelde tussen traditie en modernisering. Haar regeerperiode werd gekenmerkt door betrokkenheid, standvastigheid en internationale representatie.\n\nDe traditie van koninklijke merklappen is een geliefde manier geweest om belangrijke momenten vast te leggen, en dit werk vormt daar een prachtig voorbeeld van.",
    "descriptionEN": "On April 30, 1980, Princess Beatrix was inaugurated as Queen of the Netherlands, a moment of national pride and transformation. This embroidery commemorates the historic event with symbols of the Dutch monarchy, including the royal coat of arms, the crown, and the national colors.\n\nBeatrix's inauguration marked the beginning of a new era for the Dutch royal family, where she played a connecting role between tradition and modernization. Her reign was defined by dedication, resilience, and international representation.\n\nThe tradition of royal samplers has long been a cherished way to commemorate significant moments, and this piece stands as a beautiful example of that heritage.",
    "dimensions": "42x32 cm / 44x39 cm",
    "price": "€30",
    "technique": "borduurwerk",
    "year": "1980",
    "tags": [
      "1980",
      "beatrix",
      "inauguration",
      "inhuldiging",
      "koning",
      "koningin",
      "koningsdag",
      "koninklijk",
      "merklap",
      "prins",
      "prinses",
      "queen",
      "royal",
      "sampler"
    ]
  },
  {
    "image": "31.JPEG",
    "category": "molens",
    "subcategory": "molentypen",
    "titleNL": "Hollandse Stellingmolen",
    "titleEN": "Dutch Tower mill",
    "descriptionNL": "Molens zijn al eeuwenlang onlosmakelijk verbonden met het Nederlandse landschap en erfgoed. Dit borduurwerk toont een traditionele stellingmolen, een molentype dat hoog boven de omgeving uitstijgt en vaak werd gebruikt voor industriële doeleinden, zoals het malen van graan of het zagen van hout.\n\nMet hun imposante silhouet en functionele schoonheid zijn molens een blijvend symbool van Nederlandse vindingrijkheid. Door de eeuwen heen waren ze van levensbelang voor de economie en infrastructuur, en veel van deze monumenten zijn dankzij restauratie nog steeds in werking te bewonderen.",
    "descriptionEN": "Windmills have been an integral part of the Dutch landscape and heritage for centuries. This embroidery features a traditional tower mill, a type that rises high above its surroundings and was often used for industrial purposes such as grinding grain or sawing wood.\n\nWith their imposing silhouette and functional beauty, windmills remain enduring symbols of Dutch ingenuity. Throughout history, they have been essential to the economy and infrastructure, and thanks to restoration efforts, many of these historic structures can still be admired in operation today.",
    "dimensions": "15x15 cm",
    "price": "€15",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "Dutch landscape",
      "Nederlands landschap",
      "erfgoed",
      "heritage",
      "industrie",
      "industry",
      "molen",
      "stellingmolen",
      "tower mill",
      "windmill",
      "windmolen"
    ]
  },
  {
    "image": "32.JPEG",
    "category": "molens",
    "subcategory": "molentypen",
    "titleNL": "Grondzeiler aan het Water",
    "titleEN": "Hollow Post Mill by the Water",
    "descriptionNL": "In het uitgestrekte Nederlandse landschap sieren talloze molens de horizon, elk met hun eigen functie en verhaal. Dit borduurwerk toont een achtkante grondzeiler, een van de meest iconische molentypes in Nederland. De naam verwijst naar de achthoekige vorm van de romp en het feit dat de wieken tot dicht bij de grond reiken, waardoor de molen direct door de wind kan worden aangedreven.\n\nGrondzeilers werden veelal gebruikt voor het malen van graan of het bemalen van polders en speelden een essentiële rol in de agrarische en waterhuishouding van Nederland. In dit borduurwerk zien we een kenmerkend tafereel: de molen aan het water, een herinnering aan de nauwe relatie tussen Nederland en het beheersen van het landschap.\n\nVeel van deze historische bouwwerken zijn nog steeds in bedrijf en vormen een tastbare verbinding met het verleden.",
    "descriptionEN": "Across the vast Dutch landscape, countless windmills dot the horizon, each with its own purpose and story. This embroidery features an octagonal hollow post mill, one of the most iconic windmill types in the Netherlands. Its name comes from its eight-sided base and the low-reaching sails, which allow it to harness the wind directly from ground level.\n\nHollow post mills were commonly used for grinding grain and draining polders, playing an essential role in Dutch agriculture and water management. This embroidery captures a quintessential scene: a windmill by the water, a reminder of the Netherlands' centuries-old battle against water and mastery of the landscape.\n\nMany of these historic structures remain in operation today, forming a tangible connection to the past.",
    "dimensions": "15x15 cm",
    "price": "€15",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "achtkantig",
      "grondzeiler",
      "hollow post mill",
      "molen",
      "octagonal",
      "polders",
      "water management",
      "waterbeheersing",
      "windmill",
      "windmolen"
    ]
  },
  {
    "image": "33.JPEG",
    "category": "molens",
    "subcategory": "molentypen",
    "titleNL": "Stellingmolen aan de Waterkant",
    "titleEN": "Tower Mill by the Water",
    "descriptionNL": "In het Nederlandse landschap, waar wind en water altijd in beweging zijn, vormen molens een onmiskenbaar herkenningspunt. Dit borduurwerk toont een stellingmolen, een type molen dat hoog boven de bebouwing uittorent en vaak werd gebruikt in stedelijke gebieden of bij industriële toepassingen. De naam verwijst naar de houten omloop, of stelling, halverwege de molen, waarop de molenaar de wieken kon bedienen.\n\nIn deze voorstelling staat de molen aan het water, een vertrouwd beeld in Nederland waar molens vaak strategisch werden geplaatst voor zowel wind als transport over water.\n\nDit borduurwerk brengt niet alleen de schoonheid van het ambachtelijke molenontwerp tot leven, maar herinnert ons ook aan de technologische vindingrijkheid van de Nederlanders in hun strijd tegen het water.",
    "descriptionEN": "In the Dutch landscape, where wind and water are always in motion, windmills are an unmistakable landmark. This embroidery features a tower mill, a type of windmill that rises high above its surroundings and was often used in urban areas or for industrial purposes. Its name refers to the wooden platform (stelling) halfway up the structure, where the miller could operate the sails.\n\nIn this depiction, the windmill stands by the water—a familiar sight in the Netherlands, where mills were often strategically placed to harness both wind power and water transport.\n\nThis embroidery not only brings to life the craftsmanship of traditional windmill design but also reminds us of the technological ingenuity of the Dutch in their centuries-old battle against water.",
    "dimensions": "13x15 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "industrial",
      "industrieel",
      "molen",
      "platform",
      "stelling",
      "stellingmolen",
      "tower mill",
      "waterkant",
      "waterside",
      "windmill",
      "windmolen"
    ]
  },
  {
    "image": "34.JPEG",
    "category": "stadsgezichten",
    "subcategory": "algemeen-stadsgezicht",
    "titleNL": "Hollands Dorpje aan het Water",
    "titleEN": "Dutch Village by the Water",
    "descriptionNL": "Langs de Nederlandse rivieren en kanalen liggen talloze historische dorpen waar de tijd soms stil lijkt te staan. Dit borduurwerk toont een idyllisch dorpje met karakteristieke gebouwen aan het water, een beeld dat doet denken aan oude handelsplaatsen waar schepen aanmeerden en de dorpshaven het kloppende hart van de gemeenschap vormde.\n\nHet zeilschip op de voorgrond onderstreept het belang van de binnenvaart in de Nederlandse geschiedenis. Eeuwenlang waren dit soort schepen een essentieel vervoersmiddel voor handelaren en vissers, die afhankelijk waren van de waterwegen om goederen en voedsel te vervoeren.\n\nDit tafereel is een ode aan het Nederlandse erfgoed en de verbondenheid met water en handel.",
    "descriptionEN": "Along the rivers and canals of the Netherlands, countless historic villages can be found, where time seems to stand still. This embroidery depicts an idyllic village with traditional buildings by the water, evoking images of old trading hubs where ships docked and the village harbor was the beating heart of the community.\n\nThe sailing ship in the foreground highlights the importance of inland navigation in Dutch history. For centuries, these vessels were essential for traders and fishermen, who relied on waterways to transport goods and food.\n\nThe fine details in this embroidery bring the atmosphere of the village to life—the tranquil water, the traditional architecture, and the influence of wind and weather on daily life. This scene is a tribute to Dutch heritage and the nation's deep connection to water and trade.",
    "dimensions": "16x11 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "binnenvaart",
      "dorpje",
      "erfgoed",
      "handel",
      "heritage",
      "inland navigation",
      "sailing ship",
      "trade",
      "village",
      "water",
      "zeilschip"
    ]
  },
  {
    "image": "35.JPEG",
    "category": "stadsgezichten",
    "subcategory": "algemeen-stadsgezicht",
    "titleNL": "Hollandse Molen en Zeilschip",
    "titleEN": "Dutch Windmill and Sailing Ship",
    "descriptionNL": "Molens en water vormen samen een iconisch beeld van Nederland. Dit borduurwerk vangt deze harmonieuze combinatie in een gedetailleerde voorstelling van een molen aan het water, met een zeilschip op de voorgrond.\n\nDe molen, een essentieel werktuig in de Nederlandse economie, werd niet alleen gebruikt voor het malen van graan, maar ook voor het droogmalen van land. De nabijheid van een zeilschip suggereert een tijd waarin molens en scheepvaart nauw verbonden waren: molenproducten zoals meel of gezaagd hout werden vaak via waterwegen vervoerd naar handelsstadsgezichten en havens.\n\nDit tafereel roept de sfeer op van een tijd waarin Nederland groot werd door zijn innovatieve gebruik van natuurlijke elementen: wind voor energie, water voor transport en handel.",
    "descriptionEN": "Windmills and water together form an iconic image of the Netherlands. This embroidery captures this harmonious combination in a detailed depiction of a windmill by the water, with a sailing ship in the foreground.\n\nThe windmill, an essential tool in the Dutch economy, was used not only for grinding grain but also for reclaiming land from water. The presence of a sailing ship suggests a time when windmills and maritime trade were closely linked—mill-produced goods such as flour and sawn timber were often transported via waterways to trading cities and ports.\n\nThis scene evokes an era when the Netherlands thrived through its innovative use of natural elements: wind for energy, water for transport and trade. A beautiful tribute to both craftsmanship and landscape, highlighting the Dutch heritage that makes these elements so unique.",
    "dimensions": "16x11 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "droogmalen",
      "handel",
      "land reclamation",
      "maritime",
      "molen",
      "sailing ship",
      "scheepvaart",
      "trade",
      "water",
      "windmill",
      "zeilschip"
    ]
  },
  {
    "image": "36.JPEG",
    "category": "koninklijk",
    "subcategory": "inhuldigingen-geboorte",
    "titleNL": "Inhuldiging Koningin Beatrix (1980)",
    "titleEN": "Inauguration of Queen Beatrix (1980)",
    "descriptionNL": "Op 30 april 1980 werd Koningin Beatrix officieel ingehuldigd als vorstin van Nederland, een moment dat diep in het nationale geheugen gegrift staat. Dit borduurwerk is een eerbetoon aan die historische dag, waarop Beatrix het koningschap overnam van haar moeder, Koningin Juliana.\n\nHet ontwerp toont symbolen die sterk verbonden zijn met het koningshuis: de Nederlandse leeuw op een schild, een kroon en de nationale vlag in combinatie met het Oranje lint. Deze elementen weerspiegelen de trots en verbondenheid die veel Nederlanders voelen met het Huis van Oranje.\n\nDe inhuldiging van Beatrix markeerde een nieuw tijdperk, waarin traditie en vernieuwing hand in hand gingen. Dit borduurwerk is een tastbare herinnering aan de koninklijke geschiedenis en de manier waarop borduurkunst werd ingezet om belangrijke nationale gebeurtenissen te vereeuwigen.",
    "descriptionEN": "On April 30, 1980, Queen Beatrix was officially inaugurated as the sovereign of the Netherlands, a moment deeply etched in the nation's collective memory. This embroidery is a tribute to that historic day, when Beatrix ascended to the throne, succeeding her mother, Queen Juliana.\n\nThe design features symbols closely tied to the Dutch monarchy: the Dutch lion on a shield, a crown, and the national flag combined with the Orange ribbon. These elements reflect the pride and connection many Dutch people feel with the House of Orange.\n\nThe inauguration of Beatrix marked the beginning of a new era, where tradition and renewal went hand in hand. Crafted with dedication, this embroidery serves as a tangible reminder of royal history and the way embroidery has been used to commemorate significant national events.",
    "dimensions": "22x22 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "1980",
    "tags": [
      "1980",
      "beatrix",
      "dutch lion",
      "inauguration",
      "inhuldiging",
      "juliana",
      "koning",
      "koningin",
      "koninklijk",
      "nederlands leeuw",
      "orange",
      "oranje",
      "queen",
      "royal"
    ]
  },
  {
    "image": "37.JPEG",
    "category": "koninklijk",
    "subcategory": "inhuldigingen-geboorte",
    "titleNL": "Beatrix als Jonge Koningin",
    "titleEN": "Beatrix as a Young Queen",
    "descriptionNL": "Dit borduurwerk toont een jeugdige Koningin Beatrix, een beeld dat symbool staat voor een periode van verandering en vernieuwing in Nederland. Beatrix, geboren in 1938 en koningin van 1980 tot 2013, werd al vroeg in haar leven klaargestoomd voor haar toekomstige rol. Haar intelligentie, toewijding en moderne benadering van het koningschap maakten haar een geliefd staatshoofd.\n\nDeze afbeelding weerspiegelt een tijd waarin Beatrix als jonge vorstin haar plek innam in de Nederlandse monarchie. Het borduurwerk is niet alleen een artistieke uiting, maar ook een tastbare herinnering aan een periode waarin het koningshuis zich voorbereidde op een nieuwe generatie leiderschap.",
    "descriptionEN": "This embroidery portrays a young Queen Beatrix, an image symbolizing a period of change and renewal in the Netherlands. Born in 1938, Beatrix reigned as queen from 1980 to 2013. From an early age, she was prepared for her future role, and her intelligence, dedication, and modern approach to monarchy made her a beloved head of state.\n\nThis image reflects a time when Beatrix, as a young sovereign, took her place in the Dutch monarchy. More than just an artistic expression, this embroidery is a tangible reminder of an era when the royal family prepared for a new generation of leadership.",
    "dimensions": "24x33 cm",
    "price": "€30",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "beatrix",
      "change",
      "jonge koningin",
      "koning",
      "koningin",
      "leadership",
      "leiderschap",
      "monarchie",
      "monarchy",
      "renewal",
      "verandering",
      "vernieuwing",
      "young queen"
    ]
  },
  {
    "image": "38.JPEG",
    "category": "stadsgezichten",
    "subcategory": "iconische-panden",
    "titleNL": "Paleis op de Dam",
    "titleEN": "Royal Palace on Dam Square",
    "descriptionNL": "Het Paleis op de Dam, gelegen in het hart van Amsterdam, is een van de meest imposante en historische gebouwen van Nederland. Dit borduurwerk vangt de grootsheid van dit iconische monument, dat oorspronkelijk werd gebouwd als stadhuis van Amsterdam in de 17e eeuw, tijdens de Gouden Eeuw.\n\nMet zijn indrukwekkende gevel en klassieke architectuur is het paleis een blijvende herinnering aan de welvaart en macht van Amsterdam als wereldhandelsstad. In 1808 werd het stadhuis door Koning Lodewijk Napoleon omgevormd tot een koninklijk paleis, een functie die het tot op de dag van vandaag behoudt.\n\nHet borduurwerk symboliseert de nauwe verwevenheid tussen het koningshuis en de geschiedenis van Nederland.",
    "descriptionEN": "The Royal Palace on Dam Square, located in the heart of Amsterdam, is one of the most imposing and historic buildings in the Netherlands. This embroidery captures the grandeur of this iconic monument, originally built as Amsterdam's City Hall during the 17th century, in the Dutch Golden Age.\n\nWith its impressive façade and classical architecture, the palace remains a symbol of Amsterdam's wealth and power as a global trading hub. In 1808, King Louis Bonaparte transformed the city hall into a royal palace, a function it continues to serve to this day.\n\nThis embroidery highlights the monumental presence of the palace and symbolizes the deep connection between the Dutch monarchy and the nation's history. The Royal Palace on Dam Square remains a key venue for official royal ceremonies, including state visits and inaugurations.",
    "dimensions": "27x15 cm",
    "price": "€30",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "amsterdam",
      "architecture",
      "architectuur",
      "dam",
      "golden age",
      "gouden eeuw",
      "koninklijk",
      "lodewijk napoleon",
      "louis bonaparte",
      "palace",
      "paleis",
      "royal"
    ]
  },
  {
    "image": "38 b.JPEG",
    "category": "stadsgezichten",
    "subcategory": "iconische-panden",
    "titleNL": "Paleis op de Dam",
    "titleEN": "Royal Palace on Dam Square",
    "descriptionNL": "Het Paleis op de Dam, gelegen in het hart van Amsterdam, is een van de meest imposante en historische gebouwen van Nederland. Dit borduurwerk vangt de grootsheid van dit iconische monument, dat oorspronkelijk werd gebouwd als stadhuis van Amsterdam in de 17e eeuw, tijdens de Gouden Eeuw.\n\nMet zijn indrukwekkende gevel en klassieke architectuur is het paleis een blijvende herinnering aan de welvaart en macht van Amsterdam als wereldhandelsstad. In 1808 werd het stadhuis door Koning Lodewijk Napoleon omgevormd tot een koninklijk paleis, een functie die het tot op de dag van vandaag behoudt.\n\nHet borduurwerk symboliseert de nauwe verwevenheid tussen het koningshuis en de geschiedenis van Nederland.",
    "descriptionEN": "The Royal Palace on Dam Square, located in the heart of Amsterdam, is one of the most imposing and historic buildings in the Netherlands. This embroidery captures the grandeur of this iconic monument, originally built as Amsterdam's City Hall during the 17th century, in the Dutch Golden Age.\n\nWith its impressive façade and classical architecture, the palace remains a symbol of Amsterdam's wealth and power as a global trading hub. In 1808, King Louis Bonaparte transformed the city hall into a royal palace, a function it continues to serve to this day.\n\nThis embroidery highlights the monumental presence of the palace and symbolizes the deep connection between the Dutch monarchy and the nation's history. The Royal Palace on Dam Square remains a key venue for official royal ceremonies, including state visits and inaugurations.",
    "dimensions": "36x20 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "amsterdam",
      "architecture",
      "architectuur",
      "dam",
      "golden age",
      "gouden eeuw",
      "koninklijk",
      "lodewijk napoleon",
      "louis bonaparte",
      "palace",
      "paleis",
      "royal"
    ]
  },
  {
    "image": "39.JPEG",
    "category": "koninklijk",
    "subcategory": "inhuldigingen-geboorte",
    "titleNL": "Huwelijksmerklap Beatrix & Claus",
    "titleEN": "Wedding Sampler – Beatrix & Claus",
    "descriptionNL": "Op 10 maart 1966 gaf Prinses Beatrix haar jawoord aan Prins Claus in een ceremonie die in heel Nederland werd gevierd. Dit borduurwerk is een eerbetoon aan deze historische gebeurtenis, waarin liefde en koninklijke traditie samenkwamen.\n\nHet ontwerp toont belangrijke elementen van het koninklijk huwelijk: de kerk waarin de plechtigheid plaatsvond en Kasteel Drakensteyn, de eerste officiële woonplaats van Beatrix en Claus na hun huwelijk. Het kasteel, gelegen in Lage Vuursche, werd een thuis waar hun gezinsleven zich in relatieve rust kon ontwikkelen.\n\nHet huwelijk van Beatrix en Claus werd gezien als een nieuw begin voor de monarchie. Ondanks aanvankelijke kritiek groeide Prins Claus uit tot een van de meest geliefde leden van het koningshuis, geroemd om zijn openheid en toewijding aan sociale vraagstukken.",
    "descriptionEN": "On March 10, 1966, Princess Beatrix exchanged vows with Prince Claus in a ceremony celebrated across the Netherlands. This embroidery is a tribute to this historic occasion, where love and royal tradition came together.\n\nThe design features key elements of the royal wedding: the church where the ceremony took place and Drakensteyn Castle, the first official residence of Beatrix and Claus after their marriage. Nestled in Lage Vuursche, the castle became a home where their family life could develop in relative peace.\n\nThe marriage of Beatrix and Claus was seen as a new chapter for the monarchy. Despite initial criticism, Prince Claus became one of the most beloved members of the royal family, praised for his openness and dedication to social causes. This embroidery symbolizes the warmth and stability that this union brought to the Dutch royal house.",
    "dimensions": "45x23 cm",
    "price": "€35",
    "technique": "borduurwerk",
    "year": "1966",
    "tags": [
      "1966",
      "beatrix",
      "claus",
      "drakensteyn",
      "huwelijk",
      "koning",
      "koninklijk",
      "maart",
      "march",
      "merklap",
      "prins",
      "prinses",
      "royal",
      "sampler",
      "wedding"
    ]
  },
  {
    "image": "40.JPEG",
    "category": "zaanse",
    "subcategory": "zaanse-schans",
    "titleNL": "Zaanse Merklap",
    "titleEN": "Zaan Region Sampler",
    "descriptionNL": "Merklappen zijn al eeuwenlang een onderdeel van de Nederlandse textieltraditie. Dit bijzondere exemplaar is gewijd aan Zaanstad, een historische regio die bekendstaat om haar molens, handel en scheepsbouw.\n\nHet borduurwerk bevat kenmerkende elementen van de Zaanstreek, zoals twee molens, die verwijzen naar de cruciale rol die molens speelden in de industrie van de regio. Een bijzonder detail is de walvis, een verwijzing naar de walvisvaart die in de 17e en 18e eeuw een belangrijke economische activiteit was voor Zaandam en omgeving.\n\nMerklappen zoals deze werden traditioneel gemaakt als oefenstukken voor jonge meisjes. Dit specifieke werk, gedateerd 1988, is een moderne interpretatie van deze traditie en houdt het erfgoed van de Zaanstreek op artistieke wijze in stand.",
    "descriptionEN": "Samplers have been an integral part of Dutch textile tradition for centuries. This unique piece is dedicated to Zaanstad, a historic region renowned for its windmills, trade, and shipbuilding.\n\nThe embroidery features key elements of the Zaan region, including two windmills, symbolizing the crucial role of mills in the local industry. A striking detail is the whale, a reference to whaling, which was an important economic activity in Zaandam and its surroundings during the 17th and 18th centuries. The combination of religious, administrative, and industrial elements makes this sampler a unique historical document in textile form.\n\nTraditionally, samplers like this were created as practice pieces for young girls, helping them develop their embroidery skills. Dated 1988, this particular work is a modern interpretation of that tradition, preserving the cultural heritage of the Zaan region through textile art.",
    "dimensions": "44x44 cm",
    "price": "€30",
    "technique": "borduurwerk",
    "year": "1988",
    "tags": [
      "1988",
      "merklap",
      "molens",
      "sampler",
      "walvis",
      "walvisvaart",
      "whale",
      "whaling",
      "windmills",
      "zaan",
      "zaan sampler",
      "zaanse",
      "zaanse merklap",
      "zaanstad"
    ]
  },
  {
    "image": "41.JPEG",
    "category": "stadsgezichten",
    "subcategory": "algemeen-stadsgezicht",
    "titleNL": "Watermolen in Holland",
    "titleEN": "Watermill in Holland",
    "descriptionNL": "Nederland en molens zijn onlosmakelijk met elkaar verbonden, en dit borduurwerk brengt die relatie op prachtige wijze tot leven. Dit tafereel roept de sfeer op van het Nederlandse platteland, waar molens eeuwenlang een essentiële rol speelden in waterbeheer en voedselproductie.\n\nDe molen in dit borduurwerk is vermoedelijk een achtkante grondzeiler, een type dat vaak in open landschappen werd gebouwd en direct vanaf de grond kon worden bediend. Dit soort molens werd veelvuldig gebruikt om water uit polders te malen of graan te vermalen tot meel.\n\nBorduurwerken zoals deze zijn een artistieke ode aan het Nederlandse erfgoed en herinneren aan de tijd waarin molens het landschap bepaalden en een cruciale rol speelden in de economie.",
    "descriptionEN": "The Netherlands and windmills are inseparably linked, and this embroidery beautifully brings that connection to life. The depicted watermill stands by a tranquil waterway, with small ducks peacefully floating in the foreground. This scene evokes the serene atmosphere of the Dutch countryside, where windmills played a vital role in water management and food production for centuries.\n\nThe windmill in this embroidery is likely an octagonal hollow post mill, a type often built in open landscapes, allowing it to be operated directly from the ground. These mills were commonly used for draining polders or grinding grain into flour.\n\nEmbroidery pieces like this serve as an artistic tribute to Dutch heritage, recalling an era when windmills shaped the landscape and played a crucial role in the economy.",
    "dimensions": "15x23 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "countryside",
      "ducks",
      "eenden",
      "grondzeiler",
      "hollow post mill",
      "platteland",
      "polders",
      "water management",
      "waterbeheer",
      "watermill",
      "watermolen"
    ]
  },
  {
    "image": "42.JPEG",
    "category": "molens",
    "subcategory": "molentypen",
    "titleNL": "Stellingmolen aan de Waterkant",
    "titleEN": "Tower Mill by the Water",
    "descriptionNL": "Dit borduurwerk toont een stellingmolen, een indrukwekkend type windmolen dat vaak werd gebouwd in stedelijke gebieden of langs rivieren. Dankzij de hoge stelling—een rondom lopend platform—konden de wieken ook boven aangrenzende gebouwen uit nog voldoende wind vangen.\n\nDeze molens dienden vaak als industriemolens, gebruikt voor het malen van graan, het persen van olie of het zagen van hout.\n\nBorduurwerken zoals deze geven niet alleen een artistieke interpretatie van het landschap, maar vertellen ook het verhaal van de slimme en innovatieve manieren waarop Nederlanders hun omgeving naar hun hand zetten.",
    "descriptionEN": "This embroidery features a tower mill, an impressive type of windmill often built in urban areas or along rivers. Thanks to its high platform (stelling), the sails could still catch sufficient wind above nearby buildings.\n\nThese mills were frequently used as industrial mills, serving purposes such as grinding grain, pressing oil, or sawing wood\n\nEmbroidery pieces like this not only offer an artistic interpretation of the landscape but also tell the story of how Dutch ingenuity shaped their environment to serve their needs.",
    "dimensions": "13x12 cm",
    "price": "€20",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "industrial",
      "industrie",
      "molen",
      "platform",
      "stedelijk",
      "stelling",
      "stellingmolen",
      "tower mill",
      "urban",
      "waterkant",
      "waterside",
      "windmolen"
    ]
  },
  {
    "image": "43.JPEG",
    "category": "zaanse",
    "subcategory": "zaanse-schans",
    "titleNL": "Houten Huisjes van de Zaanstreek",
    "titleEN": "Wooden Houses of the Zaan Region",
    "descriptionNL": "Dit borduurwerk toont de karakteristieke Zaanse huisjes, een typerend beeld voor de historische Zaanstreek. De groene houten gevels en witte kozijnen zijn kenmerkend voor de bouwstijl die in de 17e en 18e eeuw populair werd in deze regio. Deze huizen, vaak bewoond door welgestelde kooplieden en moleneigenaren, getuigen van de bloeiende handel en industrie die de Zaanstreek beroemd maakte.\n\nOp de achtergrond is een molen zichtbaar, een onmisbaar element in de Zaanse geschiedenis. De combinatie van waterwegen, molens en de karakteristieke bebouwing maakt de Zaanstreek tot een van de meest iconische plekken in Nederland.\n\nBorduurwerken zoals deze dienden in het verleden vaak als herinneringsstukken of souvenirs.",
    "descriptionEN": "This embroidery depicts the distinctive Zaanse houses, a defining feature of the historic Zaan region. The green wooden facades and white window frames characterize an architectural style that became popular in the 17th and 18th centuries. These houses, often inhabited by wealthy merchants and mill owners, reflect the flourishing trade and industry that made the Zaan region famous.\n\nIn the background, a windmill is visible—an essential element of Zaanse history. The combination of waterways, windmills, and characteristic buildings makes the Zaan region one of the most iconic places in the Netherlands.\n\nEmbroidery pieces like this not only capture architectural heritage but also a way of life. In the past, such works often served as keepsakes or souvenirs, a way to bring a beloved landscape into the home. This piece is a beautiful example of how textile art helps preserve cultural heritage.",
    "dimensions": "20x12 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "green facades",
      "groene gevels",
      "kooplieden",
      "merchants",
      "mill owners",
      "moleneigenaren",
      "waterways",
      "waterwegen",
      "zaan",
      "zaanse",
      "zaanse houses",
      "zaanse huisjes",
      "zaanstreek"
    ]
  },
  {
    "image": "44.JPEG",
    "category": "koninklijk",
    "subcategory": "wapens-deviezen",
    "titleNL": "Nederlandse Heraldiek",
    "titleEN": "Dutch Heraldry",
    "descriptionNL": "Heraldiek, de kunst van wapenschilden en symbolen, speelt al eeuwenlang een belangrijke rol in de Nederlandse geschiedenis. Dit borduurwerk is een eerbetoon aan die traditie en toont een verzameling wapens, waaronder het wapen van Nederland, geflankeerd door de koninklijke leeuwen.\n\nDaarnaast zijn er wapenschilden van diverse stadsgezichten en regio's te zien, zoals Amsterdam, Den Haag, Leeuwarden en Assen. Wapenschilden dienden in het verleden als visuele identificatie voor stadsgezichten, edelen en instellingen, en droegen bij aan de trots en verbondenheid binnen een gemeenschap.\n\nDit borduurwerk is niet alleen een kunstzinnige uiting, maar ook een stukje nationale identiteit, vastgelegd in borduurwerk.",
    "descriptionEN": "Heraldry, the art of coats of arms and symbols, has played a significant role in Dutch history for centuries. This embroidery pays tribute to that tradition, showcasing a collection of heraldic emblems, including the national coat of arms of the Netherlands, flanked by the royal lions.\n\nAdditionally, the piece features coats of arms from various cities and regions, such as Amsterdam, The Hague, Leeuwarden, and Assen. In the past, these heraldic symbols served as visual identifiers for cities, nobles, and institutions, reinforcing pride and unity within communities.\n\nThis embroidery brings this tradition to life through textile art, preserving the rich symbolism and history of the Netherlands. It is not only an artistic expression but also a piece of national identity, meticulously captured in embroidery.",
    "dimensions": "51x32 cm",
    "price": "€30",
    "technique": "borduurwerk",
    "year": "2024",
    "tags": [
      "amsterdam",
      "assen",
      "coats of arms",
      "den haag",
      "heraldiek",
      "heraldry",
      "koninklijke leeuwen",
      "leeuwarden",
      "nederland",
      "royal lions",
      "wapenschilden"
    ]
  },
  {
    "image": "45.JPEG",
    "category": "koninklijk",
    "subcategory": "inhuldigingen-geboorte",
    "titleNL": "Huwelijk Willem-Alexander & Máxima (2002)",
    "titleEN": "Wedding of Willem-Alexander & Máxima (2002)",
    "descriptionNL": "Op 2 februari 2002 trad kroonprins Willem-Alexander in het huwelijk met Máxima Zorreguieta, een dag die de harten van velen veroverde. Dit borduurwerk viert deze bijzondere gebeurtenis met de nationale vlag, een kroontje en een sierlijk oranje lint, die de verbondenheid met het koningshuis benadrukken.\n\nHet huwelijk werd gevierd als een moment van samensmelting tussen Nederland en Argentinië, de geboortegrond van Máxima. Haar warme persoonlijkheid en oprechte betrokkenheid zorgden ervoor dat zij al snel geliefd werd bij het Nederlandse volk.\n\nDit borduurwerk legt een historisch moment vast waarop het koningshuis een nieuwe generatie verwelkomde en een liefdesverhaal werd omarmd door de natie.",
    "descriptionEN": "On February 2, 2002, Crown Prince Willem-Alexander married Máxima Zorreguieta, a day that captured the hearts of many. This embroidery celebrates this extraordinary event, featuring the national flag, a crown, and an elegant orange ribbon, symbolizing the connection to the Dutch royal family.\n\nThe wedding was seen as a union between the Netherlands and Argentina, Máxima's birthplace. Her warm personality and genuine engagement quickly endeared her to the Dutch people.\n\nThis embroidery preserves a historic moment when the royal family welcomed a new generation, and the nation embraced a love story. Royal samplers serve as a timeless tribute to a defining event in Dutch history.",
    "dimensions": "21x21 cm",
    "price": "€25",
    "technique": "borduurwerk",
    "year": "2002",
    "tags": [
      "2002",
      "argentina",
      "argentinie",
      "februari",
      "february",
      "huwelijk",
      "koning",
      "koninklijk",
      "maxima",
      "orange ribbon",
      "oranje",
      "oranje lint",
      "prins",
      "royal",
      "wedding",
      "willem-alexander"
    ]
  }
];
